name: Docker Image CI

on: 
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Docker Image Tag'     
        required: true
        default: ''

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: supervisely/docker/Dockerfile
          tags: supervisely/trans-t:${{ github.event.inputs.tag_version }}
